"""Game configuration constants."""

# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Player settings
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 30
PLAYER_SPEED = 5
PLAYER_COLOR = (0, 0, 255)  # Blue

# Player bullet settings
PLAYER_BULLET_WIDTH = 4
PLAYER_BULLET_HEIGHT = 20
PLAYER_BULLET_SPEED = 5
PLAYER_BULLET_COLOR = (255, 255, 255)  # White
PLAYER_BULLET_POOL_SIZE = 20

# Invader settings
INVADER_WIDTH = 40
INVADER_HEIGHT = 30
INVADER_SPEED_X = 5
INVADER_COLOR = (255, 0, 0)  # Red
INVADER_ROWS = 5
INVADER_COLS = 11
INVADER_START_X = 100
INVADER_START_Y = 50
INVADER_SPACING_X = 60
INVADER_SPACING_Y = 40
INVADER_MOVE_DELAY = 30  # frames
INVADER_SHOOT_DELAY = 60  # frames
INVADER_SHOOT_CHANCE = 5  # percent chance per delay interval per live invader
INVADER_DROP_DISTANCE = 20
