"""Game configuration constants."""

# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Player settings
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 30
PLAYER_SPEED = 5
PLAYER_COLOR = (0, 0, 255)  # Blue

# Player bullet settings
PLAYER_BULLET_WIDTH = 4
PLAYER_BULLET_HEIGHT = 20
PLAYER_BULLET_SPEED = 5
PLAYER_BULLET_COLOR = (255, 255, 255)  # White
PLAYER_BULLET_POOL_SIZE = 20
